-- Migracion para pedidos: Supabase como registro principal + WhatsApp como canal de confirmacion.
-- Ejecutar despues del esquema inicial de productos, pedidos y pedido_items.

alter table public.pedidos
  add column if not exists numero_pedido bigint generated by default as identity;

alter table public.pedidos
  add column if not exists origen text not null default 'web'
    check (origen in ('web', 'whatsapp', 'admin'));

alter table public.pedidos
  add column if not exists whatsapp_mensaje text;

alter table public.pedidos
  add column if not exists whatsapp_enviado boolean not null default false;

alter table public.pedidos
  add column if not exists whatsapp_enviado_en timestamptz;

create unique index if not exists pedidos_numero_pedido_uidx
  on public.pedidos(numero_pedido);

create index if not exists pedidos_telefono_idx
  on public.pedidos(cliente_telefono);

-- El cliente puede crear solamente pedidos nuevos y pendientes.
drop policy if exists "clientes pueden crear pedidos" on public.pedidos;

create policy "clientes pueden crear pedidos"
on public.pedidos for insert
to anon, authenticated
with check (
  estado = 'pendiente'
  and origen = 'web'
  and whatsapp_enviado = false
);

-- Los items se crean como parte de un pedido pendiente.
drop policy if exists "clientes pueden crear items de pedido" on public.pedido_items;

create policy "clientes pueden crear items de pedido"
on public.pedido_items for insert
to anon, authenticated
with check (
  exists (
    select 1
    from public.pedidos p
    where p.id = pedido_items.pedido_id
      and p.estado = 'pendiente'
      and p.origen = 'web'
  )
);

-- Crea el pedido y sus items atomically. El precio se toma de la base de datos,
-- no del navegador, para evitar totales manipulados desde el frontend.
create or replace function public.crear_pedido(
  p_cliente_nombre text,
  p_cliente_telefono text,
  p_tipo_pedido text,
  p_direccion_entrega text,
  p_notas text,
  p_metodo_pago text,
  p_items jsonb,
  p_costo_envio numeric default 0
)
returns table (
  pedido_id uuid,
  numero_pedido bigint,
  total numeric
)
language plpgsql
security invoker
set search_path = public
as $$
declare
  item jsonb;
  producto_actual public.productos%rowtype;
  pedido_creado public.pedidos%rowtype;
  cantidad_item integer;
  subtotal_calculado numeric := 0;
  envio_calculado numeric := greatest(coalesce(p_costo_envio, 0), 0);
begin
  if nullif(trim(p_cliente_nombre), '') is null then
    raise exception 'El nombre del cliente es obligatorio';
  end if;

  if p_tipo_pedido not in ('retiro', 'delivery') then
    raise exception 'La modalidad del pedido no es valida';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido debe contener al menos un producto';
  end if;

  if p_tipo_pedido = 'delivery'
     and nullif(trim(p_direccion_entrega), '') is null then
    raise exception 'La direccion de entrega es obligatoria';
  end if;

  -- Validar disponibilidad y calcular el subtotal con precios del servidor.
  for item in select value from jsonb_array_elements(p_items)
  loop
    cantidad_item := (item ->> 'cantidad')::integer;

    if cantidad_item is null or cantidad_item < 1 or cantidad_item > 99 then
      raise exception 'La cantidad de un producto no es valida';
    end if;

    select * into producto_actual
    from public.productos
    where id = (item ->> 'producto_id')::uuid
      and disponible = true;

    if not found then
      raise exception 'Uno de los productos ya no esta disponible';
    end if;

    subtotal_calculado := subtotal_calculado
      + (producto_actual.precio * cantidad_item);
  end loop;

  insert into public.pedidos (
    cliente_nombre,
    cliente_telefono,
    tipo_pedido,
    direccion_entrega,
    notas,
    metodo_pago,
    subtotal,
    costo_envio,
    total,
    estado,
    origen
  )
  values (
    trim(p_cliente_nombre),
    nullif(trim(p_cliente_telefono), ''),
    p_tipo_pedido,
    nullif(trim(p_direccion_entrega), ''),
    nullif(trim(p_notas), ''),
    nullif(trim(p_metodo_pago), ''),
    subtotal_calculado,
    envio_calculado,
    subtotal_calculado + envio_calculado,
    'pendiente',
    'web'
  )
  returning * into pedido_creado;

  for item in select value from jsonb_array_elements(p_items)
  loop
    cantidad_item := (item ->> 'cantidad')::integer;

    select * into producto_actual
    from public.productos
    where id = (item ->> 'producto_id')::uuid
      and disponible = true;

    insert into public.pedido_items (
      pedido_id,
      producto_id,
      nombre_producto,
      precio_unitario,
      cantidad,
      subtotal
    )
    values (
      pedido_creado.id,
      producto_actual.id,
      producto_actual.nombre,
      producto_actual.precio,
      cantidad_item,
      producto_actual.precio * cantidad_item
    );
  end loop;

  return query
  select pedido_creado.id,
         pedido_creado.numero_pedido,
         pedido_creado.total;
end;
$$;

grant execute on function public.crear_pedido(
  text, text, text, text, text, text, jsonb, numeric
) to anon, authenticated;

-- Consulta util para el panel administrativo.
create or replace view public.pedidos_resumen
with (security_invoker = true)
as
select
  p.id,
  p.numero_pedido,
  p.cliente_nombre,
  p.cliente_telefono,
  p.tipo_pedido,
  p.direccion_entrega,
  p.metodo_pago,
  p.subtotal,
  p.costo_envio,
  p.total,
  p.estado,
  p.origen,
  p.whatsapp_enviado,
  p.creado_en,
  coalesce(
    jsonb_agg(
      jsonb_build_object(
        'nombre', pi.nombre_producto,
        'cantidad', pi.cantidad,
        'precio', pi.precio_unitario,
        'subtotal', pi.subtotal
      ) order by pi.id
    ) filter (where pi.id is not null),
    '[]'::jsonb
  ) as items
from public.pedidos p
left join public.pedido_items pi on pi.pedido_id = p.id
group by p.id;
