-- La Sazon de Jessy: esquema inicial completo.
-- Ejecutar una sola vez en Supabase SQL Editor.
-- Incluye catalogo, configuracion, autenticacion admin, pedidos y WhatsApp.

create extension if not exists "pgcrypto";

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  rol text not null default 'admin' check (rol in ('admin', 'empleado')),
  creado_en timestamptz not null default now()
);

create table if not exists public.categorias (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  icono text not null default '',
  orden integer not null default 0,
  activa boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.productos (
  id uuid primary key default gen_random_uuid(),
  codigo_original integer unique,
  categoria_id uuid references public.categorias(id) on delete set null,
  nombre text not null,
  descripcion text not null default '',
  precio numeric(10,2) not null check (precio >= 0),
  imagen_url text,
  insignia text not null default '',
  disponible boolean not null default true,
  popular boolean not null default false,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.configuracion_sitio (
  id integer primary key default 1 check (id = 1),
  nombre_restaurante text not null default 'La Sazon de Jessy',
  slogan text not null default '',
  descripcion text not null default '',
  whatsapp_numero text,
  whatsapp_visible text,
  whatsapp_mensaje_bienvenida text,
  direccion text,
  referencia text,
  google_maps_url text,
  moneda text not null default '$',
  nota_pedido text,
  modo_horario text not null default 'auto'
    check (modo_horario in ('auto', 'manual_abierto', 'manual_cerrado')),
  banner_promo_activo boolean not null default true,
  banner_promo_texto text,
  beneficios jsonb not null default '[]'::jsonb,
  apariencia jsonb not null default '{}'::jsonb,
  actualizado_en timestamptz not null default now()
);

create table if not exists public.horarios (
  id uuid primary key default gen_random_uuid(),
  dia_semana integer not null unique check (dia_semana between 0 and 6),
  hora_apertura time,
  hora_cierre time,
  cerrado boolean not null default false,
  texto_visible text
);

create table if not exists public.metodos_pago (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  icono text,
  detalle text,
  activo boolean not null default true,
  orden integer not null default 0
);

create table if not exists public.pedidos (
  id uuid primary key default gen_random_uuid(),
  numero_pedido bigint generated by default as identity unique,
  cliente_nombre text not null,
  cliente_telefono text,
  tipo_pedido text not null default 'retiro'
    check (tipo_pedido in ('retiro', 'delivery')),
  direccion_entrega text,
  notas text,
  metodo_pago text,
  subtotal numeric(10,2) not null default 0 check (subtotal >= 0),
  costo_envio numeric(10,2) not null default 0 check (costo_envio >= 0),
  total numeric(10,2) not null default 0 check (total >= 0),
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'confirmado', 'preparando', 'listo', 'entregado', 'cancelado')),
  origen text not null default 'web'
    check (origen in ('web', 'whatsapp', 'admin')),
  whatsapp_mensaje text,
  whatsapp_enviado boolean not null default false,
  whatsapp_enviado_en timestamptz,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists public.pedido_items (
  id uuid primary key default gen_random_uuid(),
  pedido_id uuid not null references public.pedidos(id) on delete cascade,
  producto_id uuid references public.productos(id) on delete set null,
  nombre_producto text not null,
  precio_unitario numeric(10,2) not null check (precio_unitario >= 0),
  cantidad integer not null check (cantidad > 0),
  subtotal numeric(10,2) not null check (subtotal >= 0)
);

-- Compatibilidad si las tablas fueron creadas con una version anterior.
alter table public.configuracion_sitio
  add column if not exists banner_promo_activo boolean not null default true,
  add column if not exists banner_promo_texto text,
  add column if not exists whatsapp_mensaje_bienvenida text,
  add column if not exists beneficios jsonb not null default '[]'::jsonb,
  add column if not exists apariencia jsonb not null default '{}'::jsonb;

alter table public.productos
  add column if not exists codigo_original integer;

-- Aseguramos la restriccion en horarios por compatibilidad con versiones anteriores
create unique index if not exists horarios_dia_semana_uidx
  on public.horarios (dia_semana);

alter table public.productos
  drop constraint if exists productos_codigo_original_key;

alter table public.productos
  add constraint productos_codigo_original_key unique (codigo_original);

alter table public.pedidos
  add column if not exists numero_pedido bigint generated by default as identity,
  add column if not exists origen text not null default 'web',
  add column if not exists whatsapp_mensaje text,
  add column if not exists whatsapp_enviado boolean not null default false,
  add column if not exists whatsapp_enviado_en timestamptz;

create unique index if not exists pedidos_numero_pedido_uidx
  on public.pedidos(numero_pedido);

create index if not exists productos_categoria_idx on public.productos(categoria_id);
create index if not exists productos_disponible_idx on public.productos(disponible);
create index if not exists pedidos_estado_idx on public.pedidos(estado);
create index if not exists pedidos_creado_idx on public.pedidos(creado_en desc);
create index if not exists pedidos_telefono_idx on public.pedidos(cliente_telefono);
create index if not exists pedido_items_pedido_idx on public.pedido_items(pedido_id);

-- Funcion usada por RLS para proteger la administracion.
create or replace function public.es_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.perfiles
    where id = auth.uid() and rol in ('admin', 'empleado')
  );
$$;

-- Seguridad por fila.
alter table public.perfiles enable row level security;
alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.configuracion_sitio enable row level security;
alter table public.horarios enable row level security;
alter table public.metodos_pago enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_items enable row level security;

-- Las politicas se pueden recrear sin duplicarse.
drop policy if exists "publico puede ver categorias activas" on public.categorias;
drop policy if exists "gestion de categorias" on public.categorias;
drop policy if exists "admins gestionan categorias" on public.categorias;
create policy "gestion de categorias"
on public.categorias for all to anon, authenticated
using (true) with check (true);

drop policy if exists "publico puede ver productos disponibles" on public.productos;
drop policy if exists "publico puede ver productos" on public.productos;
drop policy if exists "gestion de productos" on public.productos;
drop policy if exists "admins gestionan productos" on public.productos;
create policy "gestion de productos"
on public.productos for all to anon, authenticated
using (true) with check (true);

drop policy if exists "publico puede ver configuracion" on public.configuracion_sitio;
drop policy if exists "gestion de configuracion" on public.configuracion_sitio;
drop policy if exists "admins gestionan configuracion" on public.configuracion_sitio;
create policy "gestion de configuracion"
on public.configuracion_sitio for all to anon, authenticated
using (true) with check (true);

drop policy if exists "publico puede ver horarios" on public.horarios;
drop policy if exists "gestion de horarios" on public.horarios;
drop policy if exists "admins gestionan horarios" on public.horarios;
create policy "gestion de horarios"
on public.horarios for all to anon, authenticated
using (true) with check (true);

drop policy if exists "publico puede ver metodos de pago" on public.metodos_pago;
drop policy if exists "publico puede ver metodos de pago" on public.metodos_pago;
drop policy if exists "gestion de metodos de pago" on public.metodos_pago;
drop policy if exists "admins gestionan metodos de pago" on public.metodos_pago;
create policy "gestion de metodos de pago"
on public.metodos_pago for all to anon, authenticated
using (true) with check (true);

drop policy if exists "clientes pueden crear pedidos" on public.pedidos;
drop policy if exists "gestion de pedidos" on public.pedidos;
drop policy if exists "admins gestionan pedidos" on public.pedidos;
create policy "gestion de pedidos"
on public.pedidos for all to anon, authenticated
using (true) with check (true);

drop policy if exists "clientes pueden crear items de pedido" on public.pedido_items;
drop policy if exists "gestion de items de pedido" on public.pedido_items;
drop policy if exists "admins gestionan items de pedido" on public.pedido_items;
create policy "gestion de items de pedido"
on public.pedido_items for all to anon, authenticated
using (true) with check (true);

-- Configuracion inicial.
insert into public.configuracion_sitio (
  id, nombre_restaurante, slogan, descripcion, whatsapp_numero, whatsapp_visible,
  whatsapp_mensaje_bienvenida, direccion, referencia, google_maps_url, moneda,
  nota_pedido, modo_horario, banner_promo_activo, banner_promo_texto,
  beneficios, apariencia
)
values (
  1,
  'La Sazon de Jessy',
  'Comida rapida con autentico sabor casero',
  'Hamburguesas, hot dogs, papi pollo, salchipapas y sanduches con ingredientes frescos y la mejor sazon de Muey.',
  '593998446974',
  '+593 998-446-974',
  'Hola La Sazon de Jessy, quiero realizar el siguiente pedido:',
  'Av. Jose Luis Tamayo, a 9 calles de la Av. Principal (Calles 14)',
  'Muey, Peninsula de Santa Elena',
  'https://www.google.com/maps/search/?api=1&query=-2.235771%2C-80.9309066',
  '$',
  'Todas nuestras ordenes incluyen papas fritas adicionales!',
  'auto',
  true,
  'Pide hoy! Todas las hamburguesas y sanduches incluyen papas fritas crocantes de cortesia.',
  '[
    {"icon":"","titulo":"Papas Fritas de Regalo","desc":"Todos los platos vienen acompanados de papas fritas recien preparadas."},
    {"icon":"","titulo":"Ingredientes Frescos","desc":"Carne de primera, salsas de la casa y panes suaves horneados al dia."},
    {"icon":"","titulo":"Atencion Rapida","desc":"Tomamos tu pedido al instante y te lo preparamos al momento."}
  ]'::jsonb,
  '{
    "colorPrimario":"#F56F06",
    "colorFondo":"#0B0704",
    "colorSuperficie":"#140D07",
    "colorTarjeta":"#1C130B",
    "colorTexto":"#FAF5F0",
    "colorTextoMuted":"#BBA999",
    "logoImagen":"./img/logo_hamburguesa.jpg",
    "heroImagen":"",
    "bannerImagen":"",
    "mostrarLogo":true,
    "mostrarBeneficios":true,
    "mostrarInformacion":true
  }'::jsonb
)
on conflict (id) do update set
  nombre_restaurante = excluded.nombre_restaurante,
  slogan = excluded.slogan,
  descripcion = excluded.descripcion,
  whatsapp_numero = excluded.whatsapp_numero,
  whatsapp_visible = excluded.whatsapp_visible,
  whatsapp_mensaje_bienvenida = excluded.whatsapp_mensaje_bienvenida,
  direccion = excluded.direccion,
  referencia = excluded.referencia,
  google_maps_url = excluded.google_maps_url,
  nota_pedido = excluded.nota_pedido,
  modo_horario = excluded.modo_horario,
  banner_promo_activo = excluded.banner_promo_activo,
  banner_promo_texto = excluded.banner_promo_texto,
  beneficios = excluded.beneficios,
  apariencia = excluded.apariencia,
  actualizado_en = now();

-- Categorias iniciales.
insert into public.categorias (id, nombre, icono, orden, activa)
values
  ('11111111-1111-1111-1111-111111111111', 'Hamburguesas', '', 1, true),
  ('22222222-2222-2222-2222-222222222222', 'Salchipapas', '', 2, true),
  ('33333333-3333-3333-3333-333333333333', 'Papi Pollo', '', 3, true),
  ('44444444-4444-4444-4444-444444444444', 'Hot Dogs', '', 4, true),
  ('55555555-5555-5555-5555-555555555555', 'Sanduches', '', 5, true)
on conflict (id) do update set
  nombre = excluded.nombre, icono = excluded.icono,
  orden = excluded.orden, activa = excluded.activa;

-- Horarios iniciales.
insert into public.horarios (dia_semana, hora_apertura, hora_cierre, cerrado, texto_visible)
values
  (1, '17:00', '23:00', false, '5:00 pm - 11:00 pm'),
  (2, '17:00', '23:00', false, '5:00 pm - 11:00 pm'),
  (3, '17:00', '23:00', false, '5:00 pm - 11:00 pm'),
  (4, '17:00', '23:00', false, '5:00 pm - 11:00 pm'),
  (5, '17:00', '23:00', false, '5:00 pm - 11:00 pm'),
  (6, '17:00', '23:00', false, '5:00 pm - 11:00 pm'),
  (0, '17:00', '23:00', false, '5:00 pm - 11:00 pm')
on conflict (dia_semana) do update set
  hora_apertura = excluded.hora_apertura,
  hora_cierre = excluded.hora_cierre,
  cerrado = excluded.cerrado,
  texto_visible = excluded.texto_visible;

-- Metodos de pago iniciales.
insert into public.metodos_pago (nombre, icono, detalle, activo, orden)
select v.nombre, v.icono, v.detalle, true, v.orden
from (values
  ('Efectivo', '', 'Al recibir tu pedido', 1),
  ('Transferencia Bancaria', '', 'Banco Pichincha / Banco Guayaquil', 2),
  ('DeUna! / Banco Pichincha', '', 'Pago rapido por codigo QR o numero', 3)
) as v(nombre, icono, detalle, orden)
where not exists (
  select 1 from public.metodos_pago m where m.nombre = v.nombre
);

-- Productos iniciales.
insert into public.productos (
  codigo_original, categoria_id, nombre, descripcion, precio, imagen_url, insignia, disponible, popular
)
values
  (1, '11111111-1111-1111-1111-111111111111', 'Hamburguesa Sencilla', 'Nuestra clasica hamburguesa con carne sazonada al grill, lechuga fresca, tomate y salsas de la casa. Incluye papas fritas.', 2.00, './img/img_hamburguesa.png', 'Clasica', true, false),
  (2, '11111111-1111-1111-1111-111111111111', 'Hamburguesa con Huevo y Queso', 'Hamburguesa clasica acompanada de huevo frito tierno y queso fundido. Incluye papas fritas.', 2.25, './img/img_hamburguesa.png', '', true, true),
  (3, '11111111-1111-1111-1111-111111111111', 'Hamburguesa con Huevo y Jamon', 'Carne jugosa al grill con huevo frito y jamon seleccionado. Incluye papas fritas adicionales.', 2.25, './img/img_hamburguesa.png', '', true, false),
  (4, '11111111-1111-1111-1111-111111111111', 'Hamburguesa con Huevo, Queso y Jamon', 'La combinacion favorita de la casa: carne, huevo, queso derretido y jamon. Con papas fritas crujientes.', 2.75, './img/img_hamburguesa.png', 'Favorita', true, true),
  (5, '11111111-1111-1111-1111-111111111111', 'Hamburguesa con Huevo y Tocino', 'Huevo frito y tocino crujiente dorado a la perfeccion. Viene con papas fritas incluidas.', 2.75, './img/img_hamburguesa.png', '', true, false),
  (6, '11111111-1111-1111-1111-111111111111', 'Hamburguesa con Huevo, Queso y Tocino', 'Una explosion de sabor con carne, huevo frito, queso fundido y tocino crujiente. Con papas fritas.', 3.00, './img/img_hamburguesa.png', 'Recomendada', true, true),
  (7, '11111111-1111-1111-1111-111111111111', 'Hamburguesa Completa', 'La reina indiscutible del menu: carne, huevo frito, queso fundido, tocino crujiente y jamon. Con papas fritas.', 3.50, './img/img_hamburguesa.png', 'La Especial', true, true),
  (8, '11111111-1111-1111-1111-111111111111', 'Hamburguesa Hawaiana', 'Delicioso contraste dulce y salado: queso fundido, tocino crujiente y dulce jalea de pina artesanal. Con papas fritas.', 2.75, './img/img_hamburguesa.png', 'Hawaiana', true, false),
  (9, '22222222-2222-2222-2222-222222222222', 'Salchipapa Tradicional', 'Papas fritas bien doradas con abundantes trozos de salchicha parrillera y salsas al gusto.', 1.75, './img/img_salchipapa.png', 'Economica', true, false),
  (10, '33333333-3333-3333-3333-333333333333', 'Papi Pollo Broster', 'Presa de pollo broster crocante por fuera y jugoso por dentro, servido sobre una generosa porcion de papas fritas.', 3.75, './img/img_papipollo.png', 'Top Ventas', true, true),
  (11, '44444444-4444-4444-4444-444444444444', 'Hot Dog Clasico', 'Pan suave y fresco, salchicha premium, papas al hilo, salsas especiales de la casa. Incluye papas fritas.', 1.60, './img/img_hotdog.png', '', true, false),
  (12, '55555555-5555-5555-5555-555555555555', 'Sanduche de Lomo de Res', 'Tierno lomo de res marinado al grill en pan baguette suave con vegetales frescos. Incluye papas fritas.', 2.50, './img/img_sanduche.png', '', true, false),
  (13, '55555555-5555-5555-5555-555555555555', 'Sanduche de Pollo', 'Filete de pechuga de pollo a la plancha con especias caseras y vegetales. Con papas fritas adicionales.', 2.50, './img/img_sanduche.png', '', true, false),
  (14, '55555555-5555-5555-5555-555555555555', 'Sanduche de Lomo Tejano', 'Lomo de res premium, tocino crujiente, queso derretido y autentica salsa BBQ ahumada. Con papas fritas.', 3.50, './img/img_sanduche.png', 'Tejano', true, true),
  (15, '55555555-5555-5555-5555-555555555555', 'Sanduche de Pollo Tejano', 'Pechuga de pollo a la plancha, tocino crujiente, queso derretido y bano de salsa BBQ ahumada. Con papas fritas.', 3.50, './img/img_sanduche.png', 'Tejano', true, true)
on conflict (codigo_original) do update set
  categoria_id = excluded.categoria_id,
  nombre = excluded.nombre,
  descripcion = excluded.descripcion,
  precio = excluded.precio,
  imagen_url = excluded.imagen_url,
  insignia = excluded.insignia,
  disponible = excluded.disponible,
  popular = excluded.popular,
  actualizado_en = now();

-- Crea un pedido y sus items validando precios y disponibilidad en el servidor.
create or replace function public.crear_pedido(
  p_cliente_nombre text,
  p_cliente_telefono text,
  p_tipo_pedido text,
  p_direccion_entrega text,
  p_notas text,
  p_metodo_pago text,
  p_items jsonb,
  p_costo_envio numeric default 0
)
returns table (pedido_id uuid, numero_pedido bigint, total numeric)
language plpgsql
security invoker
set search_path = public
as $$
declare
  item jsonb;
  producto_actual public.productos%rowtype;
  pedido_creado public.pedidos%rowtype;
  cantidad_item integer;
  subtotal_calculado numeric := 0;
  envio_calculado numeric := greatest(coalesce(p_costo_envio, 0), 0);
begin
  if nullif(trim(p_cliente_nombre), '') is null then
    raise exception 'El nombre del cliente es obligatorio';
  end if;
  if p_tipo_pedido not in ('retiro', 'delivery') then
    raise exception 'La modalidad del pedido no es valida';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido debe contener al menos un producto';
  end if;
  if p_tipo_pedido = 'delivery' and nullif(trim(p_direccion_entrega), '') is null then
    raise exception 'La direccion de entrega es obligatoria';
  end if;

  for item in select value from jsonb_array_elements(p_items)
  loop
    cantidad_item := (item ->> 'cantidad')::integer;
    if cantidad_item is null or cantidad_item < 1 or cantidad_item > 99 then
      raise exception 'La cantidad de un producto no es valida';
    end if;
    select * into producto_actual from public.productos
    where id = (item ->> 'producto_id')::uuid and disponible = true;
    if not found then
      raise exception 'Uno de los productos ya no esta disponible';
    end if;
    subtotal_calculado := subtotal_calculado + producto_actual.precio * cantidad_item;
  end loop;

  insert into public.pedidos (
    cliente_nombre, cliente_telefono, tipo_pedido, direccion_entrega, notas,
    metodo_pago, subtotal, costo_envio, total, estado, origen
  )
  values (
    trim(p_cliente_nombre), nullif(trim(p_cliente_telefono), ''), p_tipo_pedido,
    nullif(trim(p_direccion_entrega), ''), nullif(trim(p_notas), ''),
    nullif(trim(p_metodo_pago), ''), subtotal_calculado, envio_calculado,
    subtotal_calculado + envio_calculado, 'pendiente', 'web'
  )
  returning * into pedido_creado;

  for item in select value from jsonb_array_elements(p_items)
  loop
    cantidad_item := (item ->> 'cantidad')::integer;
    select * into producto_actual from public.productos
    where id = (item ->> 'producto_id')::uuid and disponible = true;
    insert into public.pedido_items (
      pedido_id, producto_id, nombre_producto, precio_unitario, cantidad, subtotal
    )
    values (
      pedido_creado.id, producto_actual.id, producto_actual.nombre,
      producto_actual.precio, cantidad_item, producto_actual.precio * cantidad_item
    );
  end loop;

  return query select pedido_creado.id, pedido_creado.numero_pedido, pedido_creado.total;
end;
$$;

grant execute on function public.crear_pedido(text, text, text, text, text, text, jsonb, numeric)
to anon, authenticated;

-- Vista para el panel administrativo. Hereda el RLS de las tablas base.
drop view if exists public.pedidos_resumen;
create view public.pedidos_resumen
with (security_invoker = true)
as
select
  p.id, p.numero_pedido, p.cliente_nombre, p.cliente_telefono,
  p.tipo_pedido, p.direccion_entrega, p.metodo_pago, p.subtotal,
  p.costo_envio, p.total, p.estado, p.origen, p.whatsapp_enviado,
  p.creado_en,
  coalesce(
    jsonb_agg(jsonb_build_object(
      'nombre', pi.nombre_producto,
      'cantidad', pi.cantidad,
      'precio', pi.precio_unitario,
      'subtotal', pi.subtotal
    ) order by pi.id) filter (where pi.id is not null),
    '[]'::jsonb
  ) as items
from public.pedidos p
left join public.pedido_items pi on pi.pedido_id = p.id
group by p.id;

-- Verificacion final: debe mostrar 15 productos.
select count(*) as total_productos from public.productos;
